import './globals.css'
import styles from './page.module.css'
import 'animate.css'
import Head from './head'
import type { Metadata } from 'next'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Head />
      <body className={inter.className}>
        <nav className={styles.nav}>
          <h1>My navbar</h1>
        </nav>
        {children}
      </body>
    </html>
  )
}
